export const data = {
  Complains: [
    {
      Category: "Complain", // Thêm trường Category
      Type: "Complain:Customer/Merchant no response",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Changes" },
        ProblemL3: { Description: "Complain customer/merchant no response" },
      },
      Details: [
        {
          Remark:
            "Dax report về việc không liên lạc được với ND để giao đơn hàng",
          Actions: [
            "Strike given to Pax",
            "Request user to submit HC Form",
            "Add remark to user's profile in Phoenix",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax not contactable when dax reached the delivery location/pick-up point",
          ],
        },
        {
          Remark: "Dax report về việc ND không có mặt tại điểm nhận hàng",
          Actions: [
            "Strike given to Pax",
            "Request user to submit HC Form",
            "Add remark to user's profile in Phoenix",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax not contactable when dax reached the delivery location/pick-up point",
          ],
        },
        {
          Remark:
            "Dax report về việc ND không ra nhận đơn hàng khi Dax giao tới",
          Actions: [
            "Strike given to Pax",
            "Request user to submit HC Form",
            "Add remark to user's profile in Phoenix",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax did not show up to receive order",
          ],
        },
      ],
    },
    {
      Category: "Complain", // Thêm trường Category
      Type: "Complain:Refused to pay",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Refuse to pay" },
      },
      Details: [
        {
          Remark:
            "- Đối tác TX phản ánh người dùng từ chối thanh toán\n- Đối tác TX báo ND hứa sẽ chuyển khoản cho Đối tác TX nhưng Đối tác TX vẫn chưa nhận được tiền. (Refuse to pay)",
          Actions: [
            "Request user to submit HC Form",
            "Contact Pax on behalf of user",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Other user did not charge/pay correct amount",
            "Pax underpaid Dax",
          ],
        },
      ],
    },
    {
      Category: "Complain", // Thêm trường Category
      Type: "Complain::Delayed at point of collection",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Complaints from users" },
        ProblemL3: {
          Description: "Dax complain Mex is taking too long to prepare order",
        },
      },
      Details: [
        {
          Remark: "Mex làm lâu",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax on cancellation fee policy",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "User Behaviour",
            "Request for refund/reimbursement",
            "DAX waited very long to collect order at mex",
          ],
        },
      ],
    },
    {
      Category: "Complain", // Added field Category
      Type: "Complain::Low Fare",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Feedback on low fare" },
      },
      Details: [
        {
          Remark:
            "- Đối tác TX phàn nàn cước phí của dịch vụ quá thấp\n- Đối tác TX yêu cầu bồi hoàn vì đã di chuyển xa hơn lộ trình thực tế.",
          Actions: [
            "Check booking/transaction details",
            "Probe for transaction details",
            "Inform Dax as per spiel",
          ],
          RootCauses: [
            "Configuration Related",
            "System Functionality",
            "Low fare generated by system",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Thêm trường Category
      Type: "Improper Job Handling",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Enquiry on Improper Job Handling" },
      },
      Details: [
        {
          Remark: "Hoàn thành sớm",
          Actions: [
            "Check for related case by user",
            "Check Dax/Pax consent to share contact details",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "Risk/Quality",
            "Dax Behaviour",
            "Dax completes the order without sending order.",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Thêm trường Category
      Type: "Reimbursement/Bonus",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Cleaning fee reimbursement" },
      },
      Details: [
        {
          Remark: "Dax nhờ hướng dẫn làm bồi hoàn do ND no show",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax on policy",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax not contactable when dax reached the delivery location/pick-up point",
          ],
        },
        {
          Remark:
            "Dax thắc mắc về một yêu cầu bồi hoàn đã gửi trước đó đã quá SLA nhưng chưa được hỗ trợ",
          Actions: [
            "Check if specified time has exceeded",
            "Advise Dax to wait for follow-up reply",
            "Assign to driver support",
          ],
          RootCauses: [
            "Indeterminable",
            "No known reason",
            "User did not receive an update after promised SLA",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Added field Category
      Type: "Enquiry::Reimbursement/Bonus",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Cleaning fee reimbursement" },
      },
      Details: [
        {
          Remark: "Dax nhờ hướng dẫn làm bồi hoàn do ND no show",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax on policy",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax not contactable when dax reached the delivery location/pick-up point",
          ],
        },
        {
          Remark:
            "Dax thắc mắc về một yêu cầu bồi hoàn đã gửi trước đó đã quá SLA nhưng chưa được hỗ trợ",
          Actions: [
            "Check if specified time has exceeded",
            "Advise Dax to wait for follow-up reply",
            "Assign to driver support",
          ],
          RootCauses: [
            "Indeterminable",
            "No known reason",
            "User did not receive an update after promised SLA",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Added field Category
      Type: "Enquiry::Fares/Surcharge/Toll",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Parking Fee Reimbursement" },
      },
      Details: [
        {
          Remark: "Dax thắc mắc về các loại phụ phí do chưa nắm rõ",
          Actions: [
            "Inform Dax accordingly",
            "Advise Dax on fare related policy",
            "Advise Dax on information received",
          ],
          RootCauses: [
            "User Training",
            "User does not know about feature/policy",
            "User wants to clarify the terms and conditions of product feature",
          ],
        },
        {
          Remark:
            "Dax report ND chưa thanh toán các loại phụ phí phát sinh cho Dax",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax on fare related policy",
            "Advise Dax on information received",
          ],
          RootCauses: [
            "User Behaviour",
            "Other user did not charge/pay correct amount",
            "Additional fee such as toll or midnight surcharge was added",
          ],
        },
        {
          Remark: "Dax yêu cầu hỗ trợ về phụ phí đợi ND lâu",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax on fare related policy",
            "Advise Dax to contact Pax directly",
          ],
          RootCauses: [
            "User Behaviour",
            "Other user did not charge/pay correct amount",
            "Waiting time fee was not added to final fare",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Added field Category
      Type: "Enquiry::App Usage(how-to)",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "App/Feature Accessibility" },
        ProblemL3: {
          Description:
            "User does not know how to use app to perform certain task",
        },
      },
      Details: [
        {
          Remark:
            "Các thắc mắc về cách sử dụng ứng dụng hoặc các vấn đề phát sinh do người gọi không biết cách kiểm tra/thao tác trên ứng dụng và cần được GS hướng dẫn ",
          Actions: [
            "Advise user on how to use product feature",
            "Inform Dax accordingly",
            "Guide Dax via in-app support",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "App issue causing difficulty to edit information directly",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Added field Category
      Type: "Enquiry::App Usage(how-to)",
      ProblemLevels: {
        ProblemL1: { Description: "Account Support" },
        ProblemL2: { Description: "GrabAcademy/Training Related" },
        ProblemL3: { Description: "Guidance on usage of app upon onboarding" },
      },
      Details: [
        {
          Remark:
            "Dax cần hướng dẫn sử dụng ứng dụng sau khi đã onboarding (Lên VP or Học khóa đào tạo)",
          Actions: [
            "Check onboarding/sign up status",
            "Follow steps found in onboarding email",
            "Assign to onboarding team",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Device/ cache/ app version issue",
          ],
        },
      ],
    },
    {
      Category: "Enquiry", // Added field Category
      Type: "Enquiry::App Usage(how-to)",
      ProblemLevels: {
        ProblemL1: { Description: "General Enquiry & Feedback" },
        ProblemL2: {
          Description: "General enquiry not related to any other category",
        },
        ProblemL3: { Description: "Enquiry on App Usage (how-to)" },
      },
      Details: [
        {
          Remark:
            "Các phản hồi thông thường về ứng dụng như yêu cầu hướng dẫn về cách sử dụng ứng dụng để thực hiện một thao tác trên app.",
          Actions: [
            "Check onboarding/sign up status",
            "Advise user on how to use product feature",
            "Assign to onboarding team",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "App version is not updated",
          ],
        },
      ],
    },
    {
      Category: "Enquiry",
      Type: "Missing Transactions/Top Up/GrabGifts",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "Missing/Inaccurate InApp Content" },
        ProblemL3: { Description: "Missing Trip/Wallet/Transaction history" },
      },
      Details: [
        {
          Remark:
            "- Tiền không được cộng vào ví nhưng thẻ đã bị trừ tiền.\n- Đối tác TX/Người dùng thắc mắc vì sao chưa thấy số tiền đã top up vào ví (đã qua giờ top-up).",
          Actions: [
            "Check top up record",
            "Assist user to top up any wallet balance",
            "Top up fare/commission to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "User performed action but app status not updated",
            "Successful top up not reflected in wallet",
          ],
        },
        {
          Remark:
            "- Tiền không được cộng vào ví nhưng thẻ đã bị trừ tiền.\n- Đối tác TX/Người dùng thắc mắc vì sao chưa thấy số tiền đã top up vào ví (đã qua giờ top-up).",
          Actions: [
            "Check top up record",
            "Assist user to top up any wallet balance",
            "Top up fare/commission to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "User performed action but app status not updated",
            "Top up not reflected in wallet",
          ],
        },
        {
          Remark:
            "- Tiền không được cộng vào ví nhưng thẻ đã bị trừ tiền.\n- Đối tác TX/Người dùng thắc mắc vì sao chưa thấy số tiền đã top up vào ví (đã qua giờ top-up).",
          Actions: [
            "Check top up record",
            "Assist user to top up any wallet balance",
            "Top up fare/commission to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Inaccurate information reflected",
            "Top up under auth status, not successfully captured",
          ],
        },
      ],
    },
    {
      Category: "Enquiry",
      Type: "Verify credit limit/cash account",
      ProblemLevels: {
        ProblemL1: { Description: "Account Support" },
        ProblemL2: { Description: "Credit Limit Related" },
        ProblemL3: { Description: "Verify credit limit" },
      },
      Details: [
        {
          Remark: "- Người gọi nhờ kiểm tra ví Cash/Credit.",
          Actions: [
            "Check for related case by user",
            "Verify that credit note is required",
            "Escalate via Top Up Channel",
          ],
          RootCauses: [
            "User Behaviour",
            "Input of incorrect information/forgot certain information",
            "Entered wrong top up amount",
          ],
        },
      ],
    },
    {
      Category: "Enquiry",
      Type: "Ban/Suspension (Deferred Cash/Credit)",
      ProblemLevels: {
        ProblemL1: { Description: "Payments & Wallet" },
        ProblemL2: { Description: "Payout/Commissions/Levy" },
        ProblemL3: { Description: "Ban/Suspension Deferred Cash/Credit" },
      },
      Details: [
        {
          Remark: "Bị BAN do vi phạm liên quan đến thái độ phục vụ",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Ban (Behavioural)",
          ],
        },
        {
          Remark: "Bị BAN do liên quan đến quấy rối",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Ban (Harassment)",
          ],
        },
        {
          Remark: "Bị BAN do hủy nhiều đơn hàng/chuyến xe",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Ban (High cancellations)",
          ],
        },
        {
          Remark: "Bị BAN do tỷ lệ hủy cao",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Ban (High CR)",
          ],
        },
        {
          Remark: "Bị BAN do tỷ lệ chấp nhận chuyến thấp",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Ban (Low DR)",
          ],
        },
        {
          Remark:
            "Bị BAN do sử dụng phần mềm của bên thứ 3 trái phép/thiết bị đã sửa đổi",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Ban (Usage of unauthorized 3rd party software/modified device)",
          ],
        },
        {
          Remark:
            "Bị tạm BAN/chấm dứt do không vượt qua được quá trình kiểm tra lý lịch",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Banned/terminated due to failed background screening",
          ],
        },
        {
          Remark: "Tài liệu đã hết hạn",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Document expired",
          ],
        },
        {
          Remark: "Do vi phạm quy tắc ứng xử",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Due to violation of code of conduct",
          ],
        },
        {
          Remark: "Bị BAN do liên quan đến Friendzone",
          Actions: [
            "Check watchtower",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Foodzone | FriendZone | ExpressZone",
          ],
        },
        {
          Remark: "Giấy phép lái xe không hợp lệ",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Invalid Driver License",
          ],
        },
        {
          Remark: "Hạn chế (Dax không thể liên lạc được)",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Restrict (Dax not contactable)",
          ],
        },
        {
          Remark: "Hạn chế",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Shadow Ban",
          ],
        },
        {
          Remark: "Tạm BAN do vi phạm liên quan đến thái độ phục vụ",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Suspend (Behavioural)",
          ],
        },
        {
          Remark: "Tạm BAN do gian lận",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Suspend (Fraud)",
          ],
        },
        {
          Remark: "Tạm BAN do quấy rối",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Suspend (Harassment)",
          ],
        },
        {
          Remark: "Tạm BAN do tỷ lệ hủy cao",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Suspend (High CR)",
          ],
        },
        {
          Remark: "Tạm BAN do hành vi không phù hợp/thô lỗ",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Suspend (Inappropriate/rude behaviour)",
          ],
        },
        {
          Remark: "Tạm BAN do tỷ lệ chấp nhận chuyến thấp",
          Actions: [
            "Educate Dax on reason for restriction",
            "Verify if reactivation is possible",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Suspensions/Restrictions/Blacklist/Ban",
            "Suspend (Low DR)",
          ],
        },
      ],
    },
    {
      Category: "Cancel",
      Type: "Cancel::Found Another Travel Option/Double Book",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Cancellation" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark:
            "- Những trường hợp ND/Đối tác tài xế nhờ huỷ đơn hàng vì lý do cá nhân của ND (đặt trùng đơn/đổi ý/đã đặt qua ứng dụng khác...)\n- Đối tác TX báo phải hủy đơn hàng/nhờ hủy đơn hàng vì lý do cá nhân của ND (đặt trùng đơn/đổi ý/đã đặt qua ứng dụng khác...)",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to cancel order/booking",
            "Add remark to user's profile in Phoenix",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax change of mind",
          ],
        },
      ],
    },
    {
      Category: "Cancel",
      Type: "Cancel::Waited Too Long",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Cancellation" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark:
            "- Những trường hợp nhờ huỷ/báo phải huỷ đơn hàng do Đối tác TX hoặc người dùng hoặc Đối tác cửa hàng bắt bên còn lại chờ quá lâu\n- Đối tác tài xế báo cáo/phàn nàn phải chờ quá lâu tại điểm giao đơn hàng.",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Waited too long and cancelled",
          ],
        },
      ],
    },
    {
      Category: "Cancel",
      Type: "Cancel::Not Contactable/No Show",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Cancellation" },
        ProblemL3: { Description: "Not contactable/No Show" },
      },
      Details: [
        {
          Remark:
            "- Đối tác TX nhờ huỷ hoặc báo huỷ đơn hàng và nhờ ghi nhận do người dùng không liên lạc được.",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax not contactable when Dax reached the delivery location/pick up point",
          ],
        },
      ],
    },
    {
      Category: "Cancel",
      Type: "Cancel::Booking Error – Wrong Address/Trial",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Cancellation" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark: "Sai địa chỉ ND",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Input of incorrect information/forgot certain information",
            "User provided the wrong address",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Booking Error – Wrong Address/Trial Device/App Related",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: {
          Description: "GPS Location/Map Support",
        },
        ProblemL3: {
          Description: "POI/App Map/GPS Location/Direction Accuracy",
        },
      },
      Details: [
        {
          Remark: "Sai định vị",
          Actions: [
            "Check location history",
            "Calculate Fare for Dax",
            "Confirm public reply sent",
          ],
          RootCauses: [
            "Configuration Related",
            "POI Configurations",
            "Bad route",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Cancel:: Too far",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Cancellation" },
        ProblemL2: { Description: "Request to help cancel" },
        ProblemL3: { Description: "Cancellation issues due to distance" },
      },
      Details: [
        {
          Remark: "Dax báo hủy/nhờ hủy CX do phát xa",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pick up location too far for Dax",
          ],
        },
        {
          Remark: "Dax báo ND nhờ hủy do Dax ở xa Mex, ND ko muốn đợi lâu",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "DAX location is too far away",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Cancel::Vehicle Breakdown",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Cancellation" },
        ProblemL2: { Description: "Vehicle Breakdown" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark:
            "Những trường hợp nhờ huỷ/báo huỷ cuốc xe và nhờ ghi nhận do Đối tác TX hư xe",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "Unforeseen circumstances",
            "Vehicle related",
            "Vehicle breakdown",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Cancel::Heavy Rain",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Cancellation" },
        ProblemL2: { Description: "Heavy Rain" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark:
            "Những trường hợp nhờ hủy cuốc xe/đơn hàng GFM/GE vì lý do trời mưa to, không thể hỗ trợ di chuyển/ giao hàng.",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "Unforeseen circumstances",
            "External and Natural events",
            "Rainy or bad weather",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Cancel::Pick Up In Emergency/Restricted Area",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Cancellation" },
        ProblemL2: { Description: "Pick Up In Emergency/Restricted Area" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX/Người dùng nhờ hủy/báo phải hủy đơn hàng do điểm lấy hàng/giao hàng nằm trong khu vực xe dừng/cấm đỗ/cấm xe lưu thông/khu vực nguy hiểm.",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Location of the pickup/delivery is dangerous",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Cancel::Cancel by mistake",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Changes" },
        ProblemL2: { Description: "Cancel by Mistake" },
        ProblemL3: { Description: "Request to undo cancellation" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX/Người dùng báo đã thao tác huỷ nhầm đơn hàng và sau đó không có thực hiện đơn hàng này.",
          Actions: [
            "Check booking/transaction details",
            "Support Pax to cancel",
            "Escalate to TM/TL",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Dax accepted the job by mistake",
          ],
        },
      ],
    },
    {
      Category: "Cancel", // Thêm trường Category
      Type: "Cancel::Not Enough Money",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Cancellation" },
        ProblemL2: { Description: "Not Enough Money" },
        ProblemL3: { Description: "Request to help cancel" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX hoặc ND nhờ huỷ/ báo huỷ đơn hàng và nhờ ghi nhận do TX không đủ tiền ứng mua đơn hàng cho ND. (Ví dụ: ứng tiền mua đơn hàng của mex CM)",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "DAX did not have enough cash on hand",
          ],
        },
      ],
    },
    {
      Category: "Invalid Contact", // Thêm trường Category
      Type: "Invalid Contact::Spam/Cannot Hear/No Text/Characters Only",
      ProblemLevels: {
        ProblemL1: { Description: "Invalid Contact" },
        ProblemL2: { Description: "Repeated contact/insufficient info" },
        ProblemL3: { Description: "Repeated Contact/Insufficient Info" },
      },
      Details: [
        {
          Remark:
            "Email/Cuộc gọi không có nội dung, nội dung không rõ ràng/tối nghĩa, hoặc người dùng/Đối tác TX gửi liên tục cố tình phá. Chat vào ứng dụng Grab nhưng hỏi về dịch vụ đối thủ.",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "User Behaviour",
            "Technical Issue",
            "User is sending spam messages/No Text/Characters Only",
          ],
        },
      ],
    },
    {
      Category: "Invalid Contact",
      Type: "Invalid Contact::Contact Disconnected",
      ProblemLevels: {
        ProblemL1: { Description: "Invalid Contact" },
        ProblemL2: { Description: "Contact Disconnected" },
        ProblemL3: { Description: "Call / Chat got disconnected" },
      },
      Details: [
        {
          Remark: "Call/Chat bị tắt khi Agent vừa join hoặc bị tắt giữa chừng",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Chat/Contact disconnected/unclear",
            "Disconnect call/chat",
          ],
        },
        {
          Remark: "Disconnect do lỗi tai nghe/máy tính",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Chat/Contact disconnected/unclear",
            "Headset/PC Issues",
          ],
        },
        {
          Remark: "Disconnect do lỗi hệ thống NICE",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Chat/Contact disconnected/unclear",
            "NICE system issue",
          ],
        },
        {
          Remark:
            "Disconnect do không nghe rõ tín hiệu từ Dax hoặc Dax không tiếp tục phản hồi",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Chat/Contact disconnected/unclear",
            "Unable to hear user clearly /No response from user",
          ],
        },
        {
          Remark: "Dax ngắt kết nối do đợi lâu",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Chat/Contact disconnected/unclear",
            "User disconnect due to long wait time",
          ],
        },
        {
          Remark: "Dax call/chat với nội dung không rõ ràng (Spam)",
          Actions: [
            "Review contact history",
            "Proceed with actions accordingly",
            "Proceed to send email/sms to Dax",
          ],
          RootCauses: [
            "Technical Issue",
            "Chat/Contact disconnected/unclear",
            "User is sending spam messages/No Text/Characters Only",
          ],
        },
      ],
    },
    {
      Category: "Report",
      Type: "Report::Parking Issue",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Parking Fee Reimbursement" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX gặp vấn đề với địa điểm giao/nhận hàng (VD: đường 1 chiều/đường cấm/đường đang sửa không vào được) và/hoặc cần nhờ hỗ trợ thu xếp 1 địa điểm đón/trả khách hoặc giao/nhận hàng khác",
          Actions: [
            "Request user to submit HC Form",
            "Probe for transaction details",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "T&C (eligibility/policies)",
            "Policy blockers for certain actions",
            "Invalid refund reason due to refund policies",
          ],
        },
      ],
    },
    {
      Category: "Report",
      Type: "Report::Protect Self From Possible Accusations",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Protect self From possible accusations" },
      },
      Details: [
        {
          Remark:
            "- Các trường hợp Đối tác TX báo cáo trước về các tình huống có thể dẫn đến tranh cãi\n- Đối tác TX báo lại đã liên hệ được với người dùng rồi, giải thích thêm về vấn đề giao hàng để tránh những cáo buộc khác",
          Actions: [
            "Check booking/transaction details",
            "Log suggestions per recommendation",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "To protect oneself from possible accusations",
          ],
        },
      ],
    },
    {
      Category: "Report",
      Type: "Report::Order too big to fulfill",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Changes" },
        ProblemL3: { Description: "Request to split order" },
      },
      Details: [
        {
          Remark:
            "Đơn đặt hàng có quá nhiều mặt hàng vượt quá khả năng giao hàng của Đối tác TX.",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "Operations",
            "Order/booking not able to be completed without GS support",
            "Order is too large for 1 DAX to deliver",
          ],
        },
      ],
    },
    {
      Category: "Report",
      Type: "Report::Send To Wrong Receiver/Recipient",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: {
          Description:
            "Dispute on incorrect commission received for booking/order",
        },
      },
      Details: [
        {
          Remark:
            "Đối tác TX/Người dùng báo về trường hợp Đối tác TX giao nhầm thức ăn/đơn hàng cho người nhận (giao nhầm đơn hàng ghép/nhầm món do lỗi của Đối tác TX).",
          Actions: [
            "Check booking/transaction details",
            "Contact Pax on behalf of user",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "Risk/Quality",
            "Dax Behaviour",
            "Dax delivered to a wrong address due to dax didn't read the address carefully",
          ],
        },
      ],
    },
    {
      Category: "Report",
      Type: "Report::Wrong Amount Deducted/Transferred/Paid",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "R&A/Fares/Fees Dispute" },
        ProblemL3: { Description: "Incorrect amount charged" },
      },
      Details: [
        {
          Remark:
            "- Các trường hợp Đối tác TX báo cáo bị trừ sai commission (VD: trừ 30% thay vì 20%)\n- Đối tác TX bị trừ sai tiền trong Ví do Tolong/TED xác nhận sai chuyến xe CNPU\n- Dùng cho các trường hợp top up qua P2P. Số tiền bị trừ/được chuyển đi không khớp (hoặc số tiền bị trừ sai hoặc số tiền chuyển đi bị sai)\n- Các trường hợp người dùng tip nhầm tiền cho đối tác tài xế/Người dùng không muốn tip nhưng bấm nhầm/người dùng có yêu cầu hoàn lại số tiền đã tip nhầm cho DTTX\n- Các trường hợp đưa nhầm tiền, thối thiếu tiền, tip nhầm mệnh giá, các trường hợp nhầm lẫn tiền mặt.\n- Gia hạn gói Hội viên và tự động trừ tiền trong ví Moca, nhưng trừ sai số tiền",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to wait for follow-up reply",
            "Escalate to TM/TL",
          ],
          RootCauses: [
            "User Behaviour",
            "Other user did not charge/pay correct amount",
            "DAX input wrong amount to charge PAX",
          ],
        },
      ],
    },

    {
      Category: "Report",
      Type: "Report::Suspect Fraud",
      ProblemLevels: {
        ProblemL1: { Description: "Safety" },
        ProblemL2: { Description: "Fake complete/Fake booking" },
        ProblemL3: { Description: "Report suspect fraud" },
      },
      Details: [
        {
          Remark:
            "- Các trường hợp Đối tác TX báo cáo về đơn hàng ảo.\n- Đối tác TX nhờ huỷ hoặc báo huỷ cuốc xe và nhờ ghi nhận do nghi ngờ người dùng có hành vi gian lận/lừa đảo",
          Actions: [
            "Check booking/transaction details",
            "Contact Dax on behalf of user",
            "Escalate to TM/TL",
          ],
          RootCauses: [
            "Risk/Quality",
            "Fraudulent activity",
            "Fake booking made by fictitious pax",
          ],
        },
      ],
    },
    {
      Category: "Tech",
      Type: "Tech::Job Not showing/Not Receiving",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "DNRJ/Allocation Issues" },
        ProblemL3: { Description: "Job not showing/DAX not receiving job" },
      },
      Details: [
        {
          Remark: "Không nhận được chuyến xe do kiểm tra lỗi ứng dụng",
          Actions: [
            "Advise Dax on information received",
            "Check for related case by user",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Configuration Related",
            "Incorrect/inaccurate system settings",
            "DAX service type does not match allocated booking",
          ],
        },
        {
          Remark: "Không nhận được chuyến xe do không đủ tiền vốn hoạt động",
          Actions: [
            "Advise Dax on information received",
            "Advise Dax to have sufficient funds in cash/credit wallet",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "T&C (eligibility/policies)",
            "Failed to perform required actions",
            "Insufficient funds in wallet balance",
          ],
        },
        {
          Remark: "Không nhận được chuyến xe do có nhiều tài xế trong khu vực",
          Actions: [
            "Advise Dax on information received",
            "Check for related case by user",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Unable to receive booking",
          ],
        },
        {
          Remark: "Không nhận được chuyến xe do nhu cầu người dùng chưa cao",
          Actions: [
            "Advise Dax on information received",
            "Check for related case by user",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: ["Indeterminable", "No known reason", "Lack of demand"],
        },
      ],
    },
    {
      Category: "Tech App General",
      Type: "Tech App General::App Stuck",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "App Stuck/Issue" },
        ProblemL3: { Description: "Tech App General stuck" },
      },
      Details: [
        {
          Remark: "Ứng dụng bị treo do lỗi thiết bị/bộ nhớ/ứng dụng",
          Actions: [
            "Check booking/transaction details",
            "Provide Dax with order/booking details",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Device/cache/app version issue",
          ],
        },
        {
          Remark: "Không thể thao tác hủy do lỗi thiết bị/bộ nhớ/ứng dụng",
          Actions: [
            "Check booking/transaction details",
            "Support Dax to cancel",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Device/cache/app version issue",
          ],
        },
        {
          Remark: "Không thể thao tác pick-up do lỗi thiết bị/bộ nhớ/ứng dụng",
          Actions: [
            "Check booking/transaction details",
            "Provide Dax with order/booking details",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Device/cache/app version issue",
          ],
        },
        {
          Remark: "Không thể thao tác hoàn thành đơn hàng",
          Actions: [
            "Check booking/transaction details",
            "Assist to force complete booking",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Unable to complete booking",
          ],
        },
      ],
    },
    {
      Category: "Tech App General",
      Type: "Tech App General::Unclear of Booking",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking details" },
        ProblemL3: { Description: "Unclear of booking" },
      },
      Details: [
        {
          Remark:
            "Các thắc mắc về thông tin/tình trạng chuyến xe (picking_up hay dropping_off, có tag business hay không, phương thức thanh toán là gì...)",
          Actions: [
            "Check booking/transaction details",
            "Process appeasement request",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "User Training",
            "User unfamiliar with feature/interface",
            "Unaware of how to view charges for booking",
          ],
        },
        {
          Remark:
            "ND phản ánh TX P3-P5, cung cấp được BSX nhưng không có thông tin booking",
          Actions: [
            "Check booking/transaction details",
            "Process appeasement request",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "User Training",
            "User unfamiliar with feature/interface",
            "Unaware of how to view charges for booking",
          ],
        },
      ],
    },
    {
      Category: "Tech App General",
      Type: "Tech App General::POI/Map/Locations",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "GPS Location/Map Support" },
        ProblemL3: { Description: "Suggestion on maps improvement" },
      },
      Details: [
        {
          Remark:
            "Các góp ý của user về việc cải thiện bản đồ (VD: cải thiện route hoặc điều hướng)",
          Actions: [
            "Check poi against actual address",
            "Calculate Fare for Dax",
            "Assign to map ops",
          ],
          RootCauses: [
            "Configuration Related",
            "POI Configurations",
            "POI is not on the map yet",
          ],
        },
        {
          Remark:
            "- Ghim vị trí trên bản đồ dax không phản ánh vị trí thực tế/Vị trí bản đồ khác với địa chỉ được cung cấp/POI hiển thị trên ứng dụng Grab khác với địa chỉ thực tế",
          Actions: [
            "Check poi against actual address",
            "Calculate Fare for Dax",
            "Update poi for Mex",
          ],
          RootCauses: [
            "Technical Issue",
            "Inaccurate information reflected",
            "Actual location and pin location in app differs",
          ],
        },
      ],
    },
    {
      Category: "Tech",
      Type: "Tech::POI/App Map/GPS Location/Direction Accuracy",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "GPS Location/Map Support" },
        ProblemL3: { Description: "GPS location inaccurate" },
      },
      Details: [
        {
          Remark:
            "Dax không thể tìm thấy vị trí của điểm picking up/dropping off/cửa hàng vì GPS hiển thị vị trí không chính xác.",
          Actions: [
            "Check poi against actual address",
            "Calculate Fare for Dax",
            "Assign to map ops",
          ],
          RootCauses: [
            "Technical Issue",
            "Inaccurate information reflected",
            "GPS mapping issue",
          ],
        },
      ],
    },
    {
      Category: "Tech",
      Type: "Tech::POI/App Map/GPS Location/Direction Accuracy",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "GPS Location/Map Support" },
        ProblemL3: { Description: "POI inaccurate" },
      },
      Details: [
        {
          Remark:
            "Dax báo cáo không thể tìm thấy vị trí của Mex hoặc Pax vì POI không chính xác.",
          Actions: [
            "Check poi against actual address",
            "Calculate Fare for Dax",
            "Update poi for Mex",
          ],
          RootCauses: [
            "Configuration Related",
            "POI Configurations",
            "Wrong POI submission by Merchant",
          ],
        },
      ],
    },
    {
      Category: "Tech",
      Type: "Tech::POI/App Map/GPS Location/Direction Accuracy",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "GPS Location/Map Support" },
        ProblemL3: {
          Description: "POI/App Map/GPS Location/Direction Accuracy",
        },
      },
      Details: [
        {
          Remark:
            "Dax báo cáo ứng dụng của anh ấy gặp vấn đề ở nhiều khía cạnh liên quan đến vị trí và định hướng.",
          Actions: [
            "Check booking/transaction details",
            "Inform Dax accordingly",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "Technical Issue",
            "Inaccurate information reflected",
            "Dax GPS issue",
          ],
        },
      ],
    },
    {
      Category: "Tech",
      Type: "Tech::POI/App Map/GPS Location/Direction Accuracy",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "GPS Location/Map Support" },
        ProblemL3: { Description: "Wrong/bad route given" },
      },
      Details: [
        {
          Remark:
            "Dax phàn nàn rằng tuyến đường được cung cấp cho họ bởi GrabMaps khá xấu hoặc không chính xác (ví dụ: Không thông báo về việc phong tỏa đường, tuyến đường dài hơn một cách không hợp lý).",
          Actions: [
            "Check poi against actual address",
            "Calculate Fare for Dax",
            "Assign to map ops",
          ],
          RootCauses: [
            "Configuration Related",
            "POI Configurations",
            "Bad route",
          ],
        },
      ],
    },
    {
      Category: "Tech",
      Type: "Tech::Force Complete",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Changes" },
        ProblemL3: { Description: "Request for forced completion" },
      },
      Details: [
        {
          Remark: "Đối tác TX/Người dùng nhờ hỗ trợ force complete chuyến xe.",
          Actions: [
            "Check booking/transaction details",
            "Update to latest app ver",
            "Assist to force complete booking",
          ],
          RootCauses: [
            "Technical Issue",
            "User unable to perform action",
            "Unable to complete booking",
          ],
        },
      ],
    },
    {
      Category: "Incentive",
      Type: "Incentive::Dispute AR/CR/DR",
      ProblemLevels: {
        ProblemL1: { Description: "Rewards/Incentives/Promo" },
        ProblemL2: { Description: "AR/CR/DR/CP related" },
        ProblemL3: { Description: "Incentive Dispute on AR/CR/DR/CP" },
      },
      Details: [
        {
          Remark: "Dax dispute/phàn nàn về tỉ lệ hủy (CR)",
          Actions: [
            "Request user to submit HC Form",
            "Explain cr info to Dax",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Dax is worried cancellation rate is affected",
          ],
        },
        {
          Remark: "Dax dispute/phàn nàn về tỉ lệ nhận (AR)",
          Actions: [
            "Check booking/transaction details",
            "Explain ar info to Dax",
            "Perform Basic Troubleshooting",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Dax is worried acceptance rate is affected",
          ],
        },
      ],
    },
    {
      Category: "Incentive",
      Type: "Incentive::Mechanism currently ineligible",
      ProblemLevels: {
        ProblemL1: { Description: "Rewards/Incentives/Promo" },
        ProblemL2: { Description: "Incentives programs" },
        ProblemL3: { Description: "Checking of eligibility for incentives" },
      },
      Details: [
        {
          Remark:
            "Dax thắc mắc/tranh cãi về việc Dax đột nhiên bị loại ra khỏi 1 chương trình thưởng nào đó",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Technical Issue",
            "Inaccurate information reflected",
            "Incentive is not showing correctly in app",
          ],
        },
        {
          Remark: "Dax thắc mắc tiền thưởng trả chậm, bị pending trên hệ thống",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Inform Dax to wait 24 hours for update to process",
          ],
          RootCauses: [
            "Technical Issue",
            "App/Software-related issue",
            "Transaction stuck in Processing/Pending/INIT State",
          ],
        },
      ],
    },
    {
      Category: "Incentive",
      Type: "Incentive::Mechanism Eligible Criteria",
      ProblemLevels: {
        ProblemL1: { Description: "Rewards/Incentives/Promo" },
        ProblemL2: { Description: "Incentives programs" },
        ProblemL3: { Description: "Checking of eligibility for incentives" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX hỏi về chương trình thưởng hoặc các tiêu chí đạt thưởng (giới hạn khu vực/khung giờ, số cuốc xe, điểm đánh giá...) của một chương trình nào đó",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Advise Dax on policy",
          ],
          RootCauses: [
            "T&C (eligibility/policies)",
            "User did not meet criteria/ are not in selected group",
            "DAX did not meet the full criteria in order to get the incentive",
          ],
        },
        {
          Remark:
            "Đối tác TX hỏi về chương trình thưởng hoặc các tiêu chí đạt thưởng (giới hạn khu vực/khung giờ, số cuốc xe, điểm đánh giá...) của một chương trình nào đó",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Advise Dax on policy",
          ],
          RootCauses: [
            "T&C (eligibility/policies)",
            "User did not meet criteria/ are not in selected group",
            "Did not meet criteria",
          ],
        },
      ],
    },
    {
      Category: "Incentive",
      Type: "Incentive::Mechanism Eligible Criteria",
      ProblemLevels: {
        ProblemL1: { Description: "Rewards/Incentives/Promo" },
        ProblemL2: { Description: "Incentives programs" },
        ProblemL3: { Description: "Payout eligibility" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX hỏi về chương trình thưởng hoặc các tiêu chí đạt thưởng (giới hạn khu vực/khung giờ, số cuốc xe, điểm đánh giá...) của một chương trình nào đó",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Advise Dax on policy",
          ],
          RootCauses: [
            "T&C (eligibility/policies)",
            "User did not meet criteria/ are not in selected group",
            "Booking was ineligible for ride cover voucher",
          ],
        },
        {
          Remark:
            "Đối tác TX hỏi về chương trình thưởng hoặc các tiêu chí đạt thưởng (giới hạn khu vực/khung giờ, số cuốc xe, điểm đánh giá...) của một chương trình nào đó",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Advise Dax on policy",
          ],
          RootCauses: [
            "T&C (eligibility/policies)",
            "User did not meet criteria/ are not in selected group",
            "DAX did not meet the full criteria in order to get the incentive",
          ],
        },
      ],
    },
    {
      Category: "Incentive",
      Type: "Incentive::Mechanism currently ineligible",
      ProblemLevels: {
        ProblemL1: { Description: "Rewards/Incentives/Promo" },
        ProblemL2: { Description: "Incentives programs" },
        ProblemL3: { Description: "Checking of eligibility for incentives" },
      },
      Details: [
        {
          Remark:
            "Đối tác TX thắc mắc/tranh cãi về việc Đối tác TX đột nhiên bị loại ra khỏi 1 chương trình thưởng nào đó dù trước đó Đối tác TX vẫn được ghi nhận đang tham gia/đủ điều kiện tham gia",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Inform Dax accordingly",
          ],
          RootCauses: [
            "Technical Issue",
            "Inaccurate information reflected",
            "Incentive is not showing correctly in app",
          ],
        },
        {
          Remark:
            "Đối tác TX thắc mắc/tranh cãi về việc Đối tác TX đột nhiên bị loại ra khỏi 1 chương trình thưởng nào đó dù trước đó Đối tác TX vẫn được ghi nhận đang tham gia/đủ điều kiện tham gia",
          Actions: [
            "Check the transaction status in Phoenix",
            "Inform Dax about eligibility criteria",
            "Inform Dax to wait 24 hours for update to process",
          ],
          RootCauses: [
            "Technical Issue",
            "App/Software-related issue",
            "Transaction stuck in Processing/Pending/INIT State",
          ],
        },
      ],
    },

    {
      Category: "Registration",
      Type: "Registration::Fees/Requirements/Terms and Conditions (chung)",
      ProblemLevels: {
        ProblemL1: { Description: "Account Support" },
        ProblemL2: { Description: "Activation/ Re-activation/ Sign Up/Opt In" },
        ProblemL3: {
          Description: "Registration fees/requirements/terms and conditions",
        },
      },
      Details: [
        {
          Remark:
            "Chủ xe/Đối tác TX thắc mắc về lệ phí đăng ký, về thủ tục & điều kiện để trở thành đối tác của Grab (thời gian xét duyệt, tiêu chuẩn hồ sơ, quy trình đào tạo/tái đào tạo), hoặc về các quy tắc ứng xử/quy định chế tài của Grab, đồ trang bị GF...",
          Actions: [
            "Inform Dax accordingly",
            "Advise Dax on policy",
            "Advise Dax on information received",
          ],
          RootCauses: [
            "User Training",
            "User does not know about feature/policy",
            "User wants to clarify the terms and conditions of product feature",
          ],
        },
        {
          Remark:
            "GFM: Overall về GF: quy trình thanh toán, cách thức hoạt động, quyền lợi, CoC...",
          Actions: [
            "Inform Dax accordingly",
            "Advise Dax on policy",
            "Advise Dax on information received",
          ],
          RootCauses: [
            "User Training",
            "User does not know about feature/policy",
            "User wants to clarify the terms and conditions of product feature",
          ],
        },
      ],
    },
    {
      Category: "Change Info",
      Type: "Change Info::Delivery Address",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Changes" },
        ProblemL3: {
          Description: "Request to change delivery/drop off address",
        },
      },
      Details: [
        {
          Remark: "Người dùng nhờ thay đổi địa điểm giao đơn hàng",
          Actions: [
            "Check booking/transaction details",
            "Calculate Fare for Dax",
            "Advise Dax on fare related policy",
          ],
          RootCauses: [
            "User Behaviour",
            "Input of incorrect information/forgot certain information",
            "User provided the wrong address",
          ],
        },
        {
          Remark: "Đối tác TX báo ND muốn thay đổi địa điểm giao đơn hàng",
          Actions: [
            "Check booking/transaction details",
            "Calculate Fare for Dax",
            "Advise Dax on fare related policy",
          ],
          RootCauses: [
            "User Behaviour",
            "Input of incorrect information/forgot certain information",
            "User provided the wrong address",
          ],
        },
      ],
    },
    {
      Category: "Change Info",
      Type: "Change Info::Fleet/Insurance/Model/Plate/Reg/Type",
      ProblemLevels: {
        ProblemL1: { Description: "Account Support" },
        ProblemL2: { Description: "Change Account Information" },
        ProblemL3: {
          Description: "Fleet/insurance/model/plate/reg/type update",
        },
      },
      Details: [
        {
          Remark:
            "Những yêu cầu thay đổi/cập nhật hoặc hỏi về tình trạng cập nhật thông tin pháp nhân (HĐối tác TX)/bảo hiểm/đời xe/biển số xe/thông tin đăng kiểm/loại xe/chuyển vùng hoạt động",
          Actions: [
            "Check onboarding/sign up status",
            "Advise Dax on policy",
            "Update fleet info",
          ],
          RootCauses: [
            "Operations",
            "Changing certain account/merchant information",
            "Insurance/Cover Note Expired/Expiring",
          ],
        },
      ],
    },
    {
      Category: "Request",
      Type: "Request::Details After Trip/Order Complete",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Details" },
        ProblemL3: {
          Description: "Request for details after trip/order complete",
        },
      },
      Details: [
        {
          Remark:
            "Đối tác TX hỏi xin thông tin người dùng (hoặc ngược lại) sau khi chuyến xe đã kết thúc",
          Actions: [
            "Check booking/transaction details",
            "Contact Pax on behalf of user",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "Risk/Quality",
            "Dax Behaviour",
            "Dax missed out some item when picking up or delivering",
          ],
        },
        {
          Remark:
            "Đối tác TX/Người dùng yêu cầu xem/gửi lại hợp đồng điện tử (e-contract) sau khi chuyến xe đã hoàn thành",
          Actions: [
            "Check booking/transaction details",
            "Contact Pax on behalf of user",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "Risk/Quality",
            "Dax Behaviour",
            "Dax missed out some item when picking up or delivering",
          ],
        },
      ],
    },
    {
      Category: "Feedback",
      Type: "Feedback::Features Improvement",
      ProblemLevels: {
        ProblemL1: { Description: "General Enquiry & Feedback" },
        ProblemL2: { Description: "Suggestions/Ideas on Grab" },
        ProblemL3: { Description: "Suggestion to Grab for consideration" },
      },
      Details: [
        {
          Remark: "Các phản hồi hoặc góp ý cải thiện tính năng của dịch vụ",
          Actions: [
            "Inform Dax accordingly",
            "Advise Dax on policy",
            "Advise Dax on information received",
          ],
          RootCauses: [
            "User Training",
            "User does not know about feature/policy",
            "Unaware of prevailing policy or recent policy changes",
          ],
        },
        {
          Remark:
            "Đối tác TX thắc mắc hoặc phản ánh về Job Masking (tính năng ẩn thông tin chuyến xe)",
          Actions: [
            "Inform Dax accordingly",
            "Advise Dax on policy",
            "Advise Dax on information received",
          ],
          RootCauses: [
            "User Training",
            "User does not know about feature/policy",
            "Unaware of prevailing policy or recent policy changes",
          ],
        },
      ],
    },
    {
      Category: "P4", // Thêm trường Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Shop details incorrect" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Mex đóng cửa",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Inform Dax to contact Mex",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Store was closed when DAX arrived",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Item out of stock" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Mex hết món",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Inform Dax to contact Mex",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Item is out of stock / not available",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "Device/App Related" },
        ProblemL2: { Description: "Device Issue/Support" },
        ProblemL3: { Description: "MEX reports issue with Grab Device" },
      },
      Details: [
        {
          Remark: "Mex từ chối nhận đơn",
          Actions: [
            "Request user to submit HC Form",
            "Advise Dax to cancel order/booking",
            "Check booking/transaction details",
          ],
          RootCauses: [
            "Risk/Quality",
            "Cancellation or rejection of order",
            "User had to reorder from another MEX",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Wrong item in order" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Mex giao sai món",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to contact Pax directly",
            "Advise user to report via Help Centre",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Mex made mistake in the order",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Wrong item in order" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Mex tự ý đổi/xóa món nhưng không xác nhận với ND",
          Actions: [
            "Check booking/transaction details",
            "Advise user to report via Help Centre",
            "Assign to Merchant support team",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Mex change item without informing",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Missing item in order" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Mex giao thiếu món",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to contact Pax directly",
            "Advise user to report via Help Centre",
          ],
          RootCauses: [
            "Risk/Quality",
            "Missing item in order upon delivery",
            "Lapse in MEX handling",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Did not follow customer instruction" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Mex không làm đơn theo ghi chú của ND",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to contact Pax directly",
            "Advise user to report via Help Centre",
          ],
          RootCauses: [
            "Risk/Quality",
            "Mex Behaviour",
            "Mex didn't follow customer's instruction",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "App in store pricing mismatch" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Giá của sản phẩm trên app khác với thực tế",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to cancel order/booking",
            "Assign to Merchant support team",
          ],
          RootCauses: [
            "Risk/Quality",
            "Mex Behaviour",
            "Mex has marked up the price on Grab",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Entire order incorrect" },
        ProblemL3: { Description: "Driver Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Giá của sản phẩm trên app khác với thực tế",
          Actions: [
            "Check booking/transaction details",
            "Check Dax/Pax consent to share contact details",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Dax deliver wrong item due to batch order",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Shop details incorrect" },
        ProblemL3: { Description: "Merchant Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Dax không tìm thấy địa chỉ Mex",
          Actions: [
            "Check booking/transaction details",
            "Advise Dax to cancel order/booking",
            "Assign to Merchant support team",
          ],
          RootCauses: [
            "Risk/Quality",
            "Mex Behaviour",
            "Mex didn't update the correct address on app in time",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Wrong item in order" },
        ProblemL3: { Description: "Driver Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Dax giao sai món",
          Actions: [
            "Check booking/transaction details",
            "Check Dax/Pax consent to share contact details",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "Risk/Quality",
            "Dax Behaviour",
            "Dax picked up or delivered the wrong item",
          ],
        },
      ],
    },
    {
      Category: "P4", // Added new Category
      Type: "P4 Behaviour and Ethics::Merchant Behaviour, Shop or Order Details",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Food/Mart Service Quality" },
        ProblemL2: { Description: "Missing item in order" },
        ProblemL3: { Description: "Driver Behaviour, Shop or Order Details" },
      },
      Details: [
        {
          Remark: "Dax giao thiếu món",
          Actions: [
            "Check booking/transaction details",
            "Check Dax/Pax consent to share contact details",
            "Provide Dax/Pax contact details (consent given)",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Dax missed out some items when picking up or delivering",
          ],
        },
      ],
    },
    {
      Category: "P4",
      Type: "p4_without_valid_reason",
      ProblemLevels: {
        ProblemL1: { Description: "Booking Support" },
        ProblemL2: { Description: "Booking Cancellation" },
        ProblemL3: { Description: "User wants to know cancellation reason" },
      },
      Details: [
        {
          Remark: "Hủy đơn hàng không có lý do chính đáng",
          Actions: [
            "Advise Dax to cancel order/booking",
            "Advise user to report via Help Centre",
            "Escalate to TM/TL",
          ],
          RootCauses: [
            "Risk/Quality",
            "Cancellation without valid reason",
            "DAX Request Pax to cancel the trip after accepting without valid reason",
          ],
        },
      ],
    },
    {
      Category: "P4 - During Trip",
      Type: "P4 Behaviour::Behave Impolitely During Trip",
      ProblemLevels: {
        ProblemL1: { Description: "P4 - Behaviour" },
        ProblemL2: { Description: "Behave Impolitely During Trip" },
        ProblemL3: { Description: "Not Applicable" },
      },
      Details: [
        {
          Remark: "Dax report Mex không lịch sự",
          Actions: [
            "Check booking/transaction details",
            "Encourage Dax to self serve",
            "Proceed with actions accordingly",
          ],
          RootCauses: [
            "Risk/Quality",
            "Mex Behaviour",
            "Mex impolite behavior",
          ],
        },
        {
          Remark: "Dax report ND không lịch sự",
          Actions: [
            "Check booking/transaction details",
            "Encourage Dax to self serve",
            "Activate Sayonara",
          ],
          RootCauses: [
            "User Behaviour",
            "Booking related issues (Non-fare related)",
            "Pax rude/inappropriate behaviour",
          ],
        },
      ],
    },
    {
      Category: "P5",
      Type: "p5_informational_-_alleged_and_unverified_cases",
      ProblemLevels: {
        ProblemL1: { Description: "P5 - Alleged Food Safety" },
        ProblemL2: { Description: "Food Allergy" },
        ProblemL3: { Description: "Not Applicable" },
      },
      Details: [
        {
          Remark: "Các trường hợp bị cáo buộc và chưa được xác minh",
          Actions: [
            "Check booking/transaction details",
            "Review contact history",
            "Escalate to TM/TL",
          ],
          RootCauses: [
            "Risk/Quality",
            "Food Allergy",
            "Spoiled food (i.e. slimy film, visible mold, discolouring)",
          ],
        },
      ],
    },
  ],
};
